seed: 0
logdir: "olympic_mujoco/trained/test_test_2"
input_norm_steps: 100000
n_itr: 20000
lr: 1e-4
eps: 1e-5
lam: 0.95
gamma: 0.99
anneal: true
std_dev: -1.5
entropy_coeff: 0.0
clip: 0.2
minibatch_size: 64
epochs: 3
use_gae: true
num_procs: 12
max_grad_norm: 0.05
max_traj_len: 400
no_mirror: false
mirror_coeff: 0.4
eval_freq: 100
continued: null

